<?php
    $lazy = $this->get_options('lazy-load');
?>
<div class="mage-magictabs mc-<?php echo $key;?>">
     <div class="products grid products-grid">
        <?php 
            $options            = $this->getData();
            $args['cart']       = $options['cart'];
            $args['compare']    = $options['compare'];
            $args['wishlist']   = $options['wishlist'];
            $args['review']     = $options['review'];
            if($collection->have_posts() ){
                echo '<ol class="products items" >';
                    while ( $collection->have_posts() ) : $collection->the_post();
                         wc_get_template( 'content-product.php', $args ); 
                    endwhile; 
                echo '</ol>';
            }else{
                echo '<p class="woocommerce-info">'. __('No products were found matching your selection.', 'alothemes') .'</p>';
            }
		?>
	</div>
</div>