<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-03 23:09:57
 * @@Modify Date: 2017-08-14 23:26:35
 * @@Function:
 */
 
	$options = $this->getOptions(); 
?>
<div class="box-content categories-type">
    <div class="alo-content-<?php echo rand(0,9999999); ?> magicproduct autoplay">
        <div class="block-products auto-height">
            <div class="block-title-tabs clearfix">
                <?php 
                    echo '<h3 class="category_activated">' . $this->getData('title') . '</h3>' ;
                ?>
                <ul class="magictabs" data-ajax='{"filter" :"<?php echo $this->getData('type') ?>", "number":"<?php echo $this->getData('number') ?>", "cart":"<?php echo $this->getData('cart') ?>", "compare":"<?php echo $this->getData('compare') ?>", "wishlist":"<?php echo $this->getData('wishlist') ?>", "review":"<?php echo $this->getData('review') ?>"}' >

                    <?php 
                        $categories     = $this->getData('categories');
                        $loaded         = " loaded ";
                        if($this->getData('ajax_load') != "no") $loaded = "";
                           
                        foreach($categories as $key => $value){
                            $activated  = "";
                            if($key == $this->getData('defaultSlug')){
                                $activated = " activated loaded";
                            } 
                            echo '<li class="item '. $activated . $loaded .'" data-type="'.
                                    $key .'"><span class="title">' . $value  . '</span></li>';
                        }                
                    ?>
                </ul>
            </div>
            <div class="block-content clearfix">
               
                    	<?php 
                            if($this->getData('shortcode_left') != "0"){
                                $_shortcode = '[magiccart_shortcode class="Magiccart\\\Cms\\\Block\\\Block"  identifier="' .$this->getData('shortcode_left') . '"]';
                                echo '<div class="banner-featured"><div class="left-category-editor">';
                                     do_shortcode($_shortcode);
                                echo '</div></div>';
                            }
                        ?>
                    
                        <div class="ajax_loading" style="display:none" data-url="<?php echo admin_url( 'admin-ajax.php' ); ?>"  data-action="magiccart_categories"></div>
                    <div class="content-products-featured">
                        <div class="content-products col-lg-7 col-md-7" 
                            <?php foreach($options as $key => $value){?>
                                   data-<?php echo $key; ?> = '<?php echo $value ?>'
                           <?php } ?> 
                           > 
                            <?php
                                $grid = $this->getTemplateFile('catalog/grid.phtml'); 
                                foreach($this->_products as $key => $collection){ 
                                    include $grid; 
                                }
                            ?>
                        </div>
                    </div>
                    <?php 
                        if($this->getData('shortcode_bottom') != "0"){
                            $_shortcode = '[magiccart_shortcode class="Magiccart\\\Cms\\\Block\\\Block"  identifier="' .$this->getData('shortcode_bottom') . '"]';
                            echo '<div class="bottom-category-editor">';
                                 do_shortcode($_shortcode);
                            echo '</div>';
                        }
                    ?>
               
            </div><!-- block-content -->
        </div>    
    </div>
</div>
