<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2017-08-13 21:59:01
 * @@Function:
 */

$logo = $this->getData('logo');
if(!$logo){
	// $options = magiccart_options();
 //    if( isset($options['logo-image']['url']) ){
 //        $logo = '<img src="'. $options['logo-image']['url'] .'"  alt="'.$options['logo_alt'].'" />';
 //    } else {
 //        $logo = get_bloginfo('sitename');
 //    }
}
$classer = $this->getData('el_class');
?>
<div class='site-branding <?php echo $classer ?>'>
    <a class="site-logo" href="<?php echo home_url(); ?>" title="<?php echo get_bloginfo('description'); ?>"><?php echo $logo; ?></a>
</div>
