<?php 
  $options = $this->getOptions();
  $portfolioId     = $this->getData('portfolioId');
  $visible = "visible-" . $this->getData("visible");
  $args = array(
              'type'          => 'portfolio',
              'child_of'      => 0,
              'orderby'       => 'id',
              'order'         => 'ASC',
              'hide_empty'    => false,
              'hierarchical'  => 1,
              'taxonomy'      => 'portfolio_category',
              'pad_counts'    => false,

          );
    $categories = get_categories( $args );
    $titleTab = array();
    $titleTab['all']  = __("All Portfolio", 'alothemes');
    foreach ($categories as  $value) {
      if(in_array($value->term_id, $portfolioId)){
        $titleTab[$value->term_id] = $value->name;
      }
    }
  
?>

<div class="box-portfolio <?php echo $visible; ?>">
    <div class="alo-content-<?php echo rand(0,9999999); ?> magicproduct autoplay">
        <div class="block-portfolio auto-height">
            <h2 class="project-all"><?php echo __('Our Projects', 'alothemes'); ?></h2>
            <span class="toggle-tab mobile" style="display:none"><i class="fa fa-bars"></i></span>
            <div class="block-title-tabs clearfix toggle-content">
                <ul class="magictabs">
                    <?php 
                        $i = 0;
                        foreach($titleTab as $key => $value){
                          $active = "";
                          if(!$i) $active = "activated";
                            echo '<li class="item loaded '. $active .'" data-type="'.trim($key).'"><span class="title">' . $value  . '</span></li>';
                            $i++;
                        }                
                    ?>
                </ul>
            </div>
            <div class="block-content clearfix">
              <!--   <div class="row"> -->
                    <div class="content-products content-portfolio" <?php foreach($options as $key => $value){?>
                                                           data-<?php echo $key; ?> = '<?php echo $value ?>'
                                                   <?php } ?> > 
                        <?php
                          foreach($this->_portfolio as $key => $collection){
                        ?>
                              <div class="mage-magictabs mc-<?php echo $key;?>">
                                <div class="products products-grid">
                                  <ol class="products items clearfix" >
                                    <?php
                                      while($collection->have_posts()): $collection->the_post();
                                    ?>
                                      <li class='item type-product item-portfolio'> <div class="box-content-port">
                                        <div class="port-thumb"><a href="<?php echo get_permalink(get_the_ID()); ?>"> <?php the_post_thumbnail()?></a></div>
                                        <div class="links-wrapper">
                                          <div class="links">
                                            <div class="caption">
                                              <div class="port-title"> <?php the_title()?> </div>
                                              <div class="sub-text description"> <?php the_excerpt(); ?> </div>
                                            </div>
                                            
                                            <div class="portfolio-icons">
                                              <a href="<?php echo get_permalink(get_the_ID()); ?>" target="_self" class="icon self-link "><span class=hide>hidden</span></a>
                                              <?php echo get_simple_likes_button( get_the_ID() ); ?>
                                            </div>
                                          </div>
                                        </div>
                                      </div> 
                                    </li>
                                    <?php endwhile;   ?>
                                  </ol>
                                </div>
                              </div>
                        <?php } ?>
                    </div>
               <!--  </div> end row -->
            </div> <!-- end block-content -->
        </div>    
    </div>
</div>










