<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2017-08-13 21:06:51
 * @@Function:
 */

$options  = $this->getOptions();
$selector = 'alo-content-'.rand(0,999999999);
$classer = $this->getData('el_class');
?>
<div class="box-blog <?php echo $classer ?>">
    <div class="<?php echo $selector ?>">
        <h3 class="title"><?php echo __('Lastest blog', 'alothemes'); ?></h3>
    	<div class="magicpost" <?php foreach($options as $key => $value){?>
                                               data-<?php echo $key; ?>  = '<?php echo $value; ?>'
                                       <?php } ?> >
    		<?php 
                foreach($this->_post as  $value){
                 	$idImage    = get_post_thumbnail_id($value->ID, 'medium');
                 	$image 		= wp_get_attachment_image_src($idImage,'medium');
                 	if($image){
                 		echo "<div class='item'>" . 
                       		'<a href="'. $value->guid .'"><img src="'. $image[0] .'" title="'. $value->post_title .'" alt="'. $value->post_title .'"  /></a>'
    						. '<h3 class="title-post"><a href="'. $value->guid .'">' . $value->post_title . '</a></h3>'
                     		. '<span class="date">' . date("d M", strtotime($value->post_date)) . ' / </span>'
                     		. "<span class='author'> By: " . get_the_author_meta("user_nicename", $value->post_author) ." / </span>"
                     		. "<span class='cmt'> " . $value->comment_count ." Comment(s) / </span>"
    						. "<span class='view'> " . $this->getPostViews($value->ID) ." View(s) </span>"
                     	. "</div>";
                 	}
                }
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	(function ($) {
		var magicpost  = $('.<?php echo $selector ?> .magicpost');
		if(magicpost.length) $('head').append(magicproduct(magicpost, '.item'));
    })(jQuery);
});
</script>

