<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-03 20:14:51
 * @@Modify Date: 2017-08-03 20:43:30
 * @@Function:
 */

    $data 	 = $this->getData();   
    $title   = $this->textbox('title', $data['title'], array('class' => 'regular-text', 'style' => 'width: 500px;'));
    $page    = $_GET['page'];  
    $message = isset($data['message']) ? $data['message'] : '';
?>

<div class="wrap">
    <h1>
        <?php echo __('New', 'alothemes') ?>
        <a class="page-title-action" href="?page=<?php echo $page. "&block=gird&module=cms&model=collection&view=gird"; ?>"><?php echo __('List', 'alothemes') ?></a>
        <a class="page-title-action" href="?page=<?php echo $page; ?>&action=add<?php echo "&module=cms&controller=block&view=newblock"; ?>"><?php echo __('New', 'alothemes') ?></a>
    </h1>
    <?php echo $message; ?>
     
    <form method="post" name="add-text" action='' enctype="multipart/form-data">
         <table class="form-table">
            <tbody>
                <tr>
                    <th><label><?php echo __('Title', 'alothemes') ?><span style="color:red;">*</span> : </label></th>
                    <td><?php echo $title; ?></td>
                </tr>
                <tr>
                    <th><label>Content <span style="color:red;">*</span> : </label></th>
                    <td><?php wp_editor(wp_kses_post($data['content']), 'content') ?></td>
                </tr>
            </tbody>
       </table>
        <input type="submit" name="submit" id="mp-btn-change" class="button button-primary" value="<?php echo __('Save', 'alothemes') ?>">
    </form>
</div>
