<?php 
    $data       = $this->getData();   
    $page       = $_GET['page'];
    $action     = $_GET['action']; 
    $message    =  isset($data['error']) ? $data['error'] : '';
    $addNew     = "?page={$page}&action=add&modul=shopbrand&view=newbrand";
    
    global $wc_product_attributes;
    $attribute_taxonomies = wc_get_attribute_taxonomies();
    
   	$name 		= isset($data['name']) ? $data['name'] : '' ;
    $url  		= isset($data['url']) ? $data['url'] : '' ;
    $attrType 	= isset($data['attrType']) ? substr($data['attrType'], 3) : '';
    $term 		= isset($data['term']) ? $data['term'] : '';
    $img  		= isset($data['img']) ? $data['img'] : '';
 
?>

<div class="wrap">
    <h1>
        NEW
        <a class="page-title-action" href="?page=<?php echo $page. "&block=gird&modul=Shopbrand&view=gird"; ?>"> List </a>
        <a class="page-title-action" href="<?php echo $addNew; ?>"> New </a>
    </h1>
    <?php echo $message; ?>
     
    <form method="post" name="add-text" class="ad-brand" action='' enctype="multipart/form-data">
         <table class="form-table">
            <tbody>
                <tr>
                    <th><label> Name <span style="color:red;">*</span> : </label></th>
                    <td>
						<input type="text" name="name-brand" value="<?php echo $name; ?>" style="width: 800px;" />
					</td>
                </tr>
                <tr>
                    <th><label> Url : </label></th>
                    <td>
						<input type="text" name="url-brand" value="<?php echo $url; ?>" style="width: 800px;" />
					</td>
                </tr>
                <tr>
                    <th><label> Type Attribute : </label></th>
                    <td>
						<select id="slt-type" name="type">
							<option value="-1"> -- Select Type -- </option>
							<?php 
								
								foreach($attribute_taxonomies as $value){
                                    $selected = "";
									if($attrType == $value->attribute_name){
										$selected = 'selected="selected"';
									}
									echo "<option {$selected} value='pa_{$value->attribute_name}'>{$value->attribute_label}</option>";
								}
							?>
						</select>
					</td>
                </tr>
                <tr>
                    <th><label> Terms Attribute : </label></th>
                    <td>
						<select termdefault="<?php echo $term; ?>" id="slt-term" name="term">
							<option value="-1"> -- Select Term -- </option>
						</select>
					</td>
                </tr>
                <tr>
                    <th><label> Image <span style="color:red;">*</span> : </label></th>
                    <td>
						<input type="text"  id="image_url" name="img" size="30" style="width:270px;" value="<?php echo $img;?>"  />
						<img class="img-brand" src="<?php echo $img; ?>" />
		                <input id="upload-btn" type="button" name="upload-btn" value="Select Image" class="button-img-brand button" />
		        	</td>
                </tr>
            </tbody>
       </table>
        <input type="submit" name="submit" id="mp-btn-change" class="button button-primary" value="Save Changes">
    </form>
</div>
